### ISSUE TITLE
Support Android Oreo (sdk >=26)

### ISSUE THREAD

**Issue by acious** [ProtoPie/android-arduino-bridge-sample#1]
This example can not run on android oreo.

The cause presented on below doc.
[background and broadcast changed on oreo](https://developer.android.com/about/versions/oreo/background)

This problem should be fix on ProtoPie Player apps.

**Comment by john-song** [comment]
Sorry for the late response.
It was resolved in ProtoPie Player 3.9.0.

**Comment by acious** [comment]
👍🏻👍🏻👍🏻

2019년 5월 20일 (월) 오후 12:25, john-song <notifications@github.com>님이 작성:
